# Prefacio {.unnumbered}

Rust puede ser descargado desde su [sitio oficial](https://rust-lang.org/es/tools/install/). Es lo suficientemente listo como para saber cuál es nuestro sistema y nos sugerirá el mejor modo de instalación, el cual normalmente consiste en copiar y pegar en la terminal un comando del tipo:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

El proceso es bastante automático y una vez terminado, se sugiere probar que todo fue bien ejecutando lo siguiente en la terminal:

```rust
rustc -V
```

Si la respuesta es similar a `rustc 1.92.0` y una fecha, todo ha ido bien.

Ahora toca instalar `rust-analyzer`, que es el servidor de lenguaje que nos permite agregar funcionalidad al IDE que pretendamos usar. No se sugiere alguno en específico, por lo que se es libre de utilizar el que se desee. En varios cursos recomiendan *VSCode*, *NeoVim* o *Emacs*, el punto es que todos deben configurarse para trabajar bien con el analizador. En este curso se estará utilizando *Kate*, que es un editor de texto avanzado disponible para Linux y Windows. *Kate* no necesita ser configurado, mientras esté todo lo correspondiente a Rust bien instalado, todo funciona bien por defecto.

Para utilizar *Kate* solo es necesario ejecutar lo siguiente en la terminal para instalar el analizador:

```bash
rustup component add rust-analyzer
```
